- name: Set action for key binding
  community.general.dconf:
    key: "/org/mate/desktop/keybindings/custom{{ item.id }}/action"
    value: "\"{{ item.action }}\""
    state: present

- name: Set binding for key binding
  community.general.dconf:
    key: "/org/mate/desktop/keybindings/custom{{ item.id }}/binding"
    value: "'{{ item.binding }}'"
    state: present

- name: Set name for key binding
  community.general.dconf:
    key: "/org/mate/desktop/keybindings/custom{{ item.id }}/name"
    value: "'{{ item.name }}'"
    state: present
